version: '3'

services:
  metadata-app:
    build:
      context: ./metadata_app
    image: metadata-app:v0.0.1
    ports:
    - "80:80"
  metadata-api:
    build:
      context: ./metadata_api
    image: metadata-api:v0.0.1
    ports:
    - "5000:5000"
    environment:
    - DB=mongodb://mongodb:27017
    - PYTHONUNBUFFERED=0
  mongodb:
    image: mongo:3.4.23
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null